development:
  adapter: postgresql
  encoding: unicode
  database: comfy_demo_dev
  pool: 5
  password:
    
test:
  adapter: postgresql
  encoding: unicode
  database: comfy_demo_test
  pool: 5
  password: